definitions:
  auth_service.CreateShortUrlRequest:
    properties:
      expire_date:
        type: string
      id:
        type: string
      long_url:
        type: string
      short_url:
        type: string
      user_id:
        type: string
    type: object
  auth_service.CreateShortUrlResponse:
    properties:
      craeted_at:
        type: string
      expire_date:
        type: string
      id:
        type: string
      long_url:
        type: string
      short_url:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  auth_service.CreateUserRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  auth_service.GetAllUserUrlsResponse:
    properties:
      total_count:
        type: integer
      urls:
        items:
          $ref: '#/definitions/auth_service.UrlData'
        type: array
    type: object
  auth_service.GetByCredentialsRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  auth_service.GetShortUrlResponse:
    properties:
      click_count:
        type: string
      created_at:
        type: string
      expire_date:
        type: string
      limit_click:
        type: string
      long_url:
        type: string
      short_url:
        type: string
      updated_at:
        type: string
      url_status:
        type: string
      user_id:
        type: string
    type: object
  auth_service.UpdateUserRequest:
    properties:
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  auth_service.UrlData:
    properties:
      click_count:
        type: string
      created_at:
        type: string
      expire_date:
        type: string
      id:
        type: string
      limit_click:
        type: string
      long_url:
        type: string
      short_url:
        type: string
      updated_at:
        type: string
      url_status:
        type: string
      user_id:
        type: string
    type: object
  auth_service.User:
    properties:
      created_at:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  auth_service.UserWithAuth:
    properties:
      accessToken:
        type: string
      created_at:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone:
        type: string
      refreshToken:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  http.Response:
    properties:
      data: {}
      description:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: This is a api gateway
paths:
  /login-user:
    post:
      consumes:
      - application/json
      description: Login User
      operationId: login_user
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: User data
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth_service.GetByCredentialsRequest'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Login User
      tags:
      - User
  /register-user:
    post:
      consumes:
      - application/json
      description: Register User
      operationId: register_user
      parameters:
      - description: CreateUserRequestBody
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth_service.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User data
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth_service.UserWithAuth'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Register User
      tags:
      - User
  /short-url:
    post:
      consumes:
      - application/json
      description: Create ShortUrl
      operationId: create_short_url
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth_service.CreateShortUrlRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Response Body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth_service.CreateShortUrlResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create ShortUrl
      tags:
      - urls
  /short-url/{hash}:
    get:
      consumes:
      - application/json
      description: Get ShortUrl
      operationId: get_short_url
      parameters:
      - description: short url hash
        in: path
        name: hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Response Body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth_service.GetShortUrlResponse'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get ShortUrlData
      tags:
      - urls
  /short-url/{user-id}:
    get:
      consumes:
      - application/json
      description: Get All User Urls
      operationId: get_all_user_urls
      parameters:
      - description: user id
        in: path
        name: user-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response Body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth_service.GetAllUserUrlsResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get All User Urls
      tags:
      - urls
  /sigma/{hash}:
    get:
      description: Handle Longer
      operationId: handle_longer
      parameters:
      - description: short url hash
        in: path
        name: hash
        required: true
        type: string
      responses:
        "201":
          description: Response Body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Handle Longer
      tags:
      - urls
  /url-qrcode:
    put:
      consumes:
      - application/json
      description: Convert Qrcode
      operationId: qr_code
      parameters:
      - description: tiny-url
        in: query
        name: tiny-url
        required: true
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: QR code image
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Url Convert Qrcode
      tags:
      - Qrcode
  /user:
    delete:
      consumes:
      - application/json
      description: Get User
      operationId: delete_user
      produces:
      - application/json
      responses:
        "200":
          description: Succes
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Delete User
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update User
      operationId: update_user
      parameters:
      - description: UpdateUserRequestBody
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth_service.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth_service.User'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Update User
      tags:
      - User
  /user/reset-password:
    put:
      consumes:
      - application/json
      description: Reset Password
      operationId: reset_password
      parameters:
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Update User
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
