version: '3'

services:
  
  app:
    build: .
    command: ["go", "run", "main.go"]
    privileged: true
    environment:
      GET_HOSTS_FROM: dns
      POSTGRES_DATABASE: shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_PASSWORD: admin
      REDIS_HOS: redis
      REDIS_PORT: 6379
      GIN_MODE: release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock     
      - /usr/local/bin/docker:/bin/docker
      - .:/go/src/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      GET_HOSTS_FROM: dns
      POSTGRES_DB: shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: admin