version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
  postgres-server:
    restart: always
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shortener_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
  go-app:
    build: .
    depends_on:
      - postgres-server
      - redis
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgres-server
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=shortener_db
      - REDIS_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379