version: '3'

services:
  
  app:
    build: .
    restart: always
    privileged: true
    environment:
      GET_HOSTS_FROM: dns
      POSTGRES_DATABASE: shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GIN_MODE: release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock     
      - /usr/local/bin/docker:/bin/docker
      - .:/go/src/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      GET_HOSTS_FROM: dns
      POSTGRES_DB: shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 6060:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: admin

  migrate-post:
    image: migrate/migrate
    container_name: migrate-post
    restart: always

    command: ["-path","/migrations","-database","postgres://postgres:admin@db:5432/shortener_db?sslmode=disable","up"]
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    
volumes:
  db:
  redis: