// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shortener.proto

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateShortUrlRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LongUrl              string   `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	ExpireDate           string   `protobuf:"bytes,3,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	ShortUrl             string   `protobuf:"bytes,5,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShortUrlRequest) Reset()         { *m = CreateShortUrlRequest{} }
func (m *CreateShortUrlRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShortUrlRequest) ProtoMessage()    {}
func (*CreateShortUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a64040fb43d257f, []int{0}
}

func (m *CreateShortUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShortUrlRequest.Unmarshal(m, b)
}
func (m *CreateShortUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShortUrlRequest.Marshal(b, m, deterministic)
}
func (m *CreateShortUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShortUrlRequest.Merge(m, src)
}
func (m *CreateShortUrlRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShortUrlRequest.Size(m)
}
func (m *CreateShortUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShortUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShortUrlRequest proto.InternalMessageInfo

func (m *CreateShortUrlRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateShortUrlRequest) GetLongUrl() string {
	if m != nil {
		return m.LongUrl
	}
	return ""
}

func (m *CreateShortUrlRequest) GetExpireDate() string {
	if m != nil {
		return m.ExpireDate
	}
	return ""
}

func (m *CreateShortUrlRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateShortUrlRequest) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}
	return ""
}

type CreateShortUrlResponse struct {
	ShortUrl             string   `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpireDate           string   `protobuf:"bytes,3,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	LongUrl              string   `protobuf:"bytes,5,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CraetedAt            string   `protobuf:"bytes,4,opt,name=craeted_at,json=craetedAt,proto3" json:"craeted_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShortUrlResponse) Reset()         { *m = CreateShortUrlResponse{} }
func (m *CreateShortUrlResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShortUrlResponse) ProtoMessage()    {}
func (*CreateShortUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a64040fb43d257f, []int{1}
}

func (m *CreateShortUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShortUrlResponse.Unmarshal(m, b)
}
func (m *CreateShortUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShortUrlResponse.Marshal(b, m, deterministic)
}
func (m *CreateShortUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShortUrlResponse.Merge(m, src)
}
func (m *CreateShortUrlResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShortUrlResponse.Size(m)
}
func (m *CreateShortUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShortUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShortUrlResponse proto.InternalMessageInfo

func (m *CreateShortUrlResponse) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}
	return ""
}

func (m *CreateShortUrlResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateShortUrlResponse) GetExpireDate() string {
	if m != nil {
		return m.ExpireDate
	}
	return ""
}

func (m *CreateShortUrlResponse) GetLongUrl() string {
	if m != nil {
		return m.LongUrl
	}
	return ""
}

func (m *CreateShortUrlResponse) GetCraetedAt() string {
	if m != nil {
		return m.CraetedAt
	}
	return ""
}

func (m *CreateShortUrlResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetShortUrlRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShortUrlId           string   `protobuf:"bytes,2,opt,name=short_url_id,json=shortUrlId,proto3" json:"short_url_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShortUrlRequest) Reset()         { *m = GetShortUrlRequest{} }
func (m *GetShortUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetShortUrlRequest) ProtoMessage()    {}
func (*GetShortUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a64040fb43d257f, []int{2}
}

func (m *GetShortUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShortUrlRequest.Unmarshal(m, b)
}
func (m *GetShortUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShortUrlRequest.Marshal(b, m, deterministic)
}
func (m *GetShortUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShortUrlRequest.Merge(m, src)
}
func (m *GetShortUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetShortUrlRequest.Size(m)
}
func (m *GetShortUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShortUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShortUrlRequest proto.InternalMessageInfo

func (m *GetShortUrlRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetShortUrlRequest) GetShortUrlId() string {
	if m != nil {
		return m.ShortUrlId
	}
	return ""
}

type GetShortUrlResponse struct {
	ShortUrl             string   `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpireDate           string   `protobuf:"bytes,3,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	LongUrl              string   `protobuf:"bytes,4,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShortUrlResponse) Reset()         { *m = GetShortUrlResponse{} }
func (m *GetShortUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetShortUrlResponse) ProtoMessage()    {}
func (*GetShortUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a64040fb43d257f, []int{3}
}

func (m *GetShortUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShortUrlResponse.Unmarshal(m, b)
}
func (m *GetShortUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShortUrlResponse.Marshal(b, m, deterministic)
}
func (m *GetShortUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShortUrlResponse.Merge(m, src)
}
func (m *GetShortUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetShortUrlResponse.Size(m)
}
func (m *GetShortUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShortUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShortUrlResponse proto.InternalMessageInfo

func (m *GetShortUrlResponse) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}
	return ""
}

func (m *GetShortUrlResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetShortUrlResponse) GetExpireDate() string {
	if m != nil {
		return m.ExpireDate
	}
	return ""
}

func (m *GetShortUrlResponse) GetLongUrl() string {
	if m != nil {
		return m.LongUrl
	}
	return ""
}

func (m *GetShortUrlResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetShortUrlResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateShortUrlRequest)(nil), "auth_service.CreateShortUrlRequest")
	proto.RegisterType((*CreateShortUrlResponse)(nil), "auth_service.CreateShortUrlResponse")
	proto.RegisterType((*GetShortUrlRequest)(nil), "auth_service.GetShortUrlRequest")
	proto.RegisterType((*GetShortUrlResponse)(nil), "auth_service.GetShortUrlResponse")
}

func init() {
	proto.RegisterFile("shortener.proto", fileDescriptor_6a64040fb43d257f)
}

var fileDescriptor_6a64040fb43d257f = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xd8, 0xa4, 0xcd, 0x58, 0x14, 0x56, 0x6a, 0x23, 0x22, 0x96, 0x9c, 0x3c, 0xe9,
	0xc1, 0x27, 0xa8, 0x0a, 0xd2, 0x93, 0x50, 0xe9, 0xc5, 0x4b, 0x58, 0xbb, 0x43, 0x1b, 0x08, 0x49,
	0x9c, 0x9d, 0x88, 0xaf, 0xe2, 0x03, 0x09, 0x3e, 0x96, 0x64, 0x9b, 0x68, 0x56, 0x04, 0x7b, 0xea,
	0x71, 0xff, 0x7f, 0x67, 0xf8, 0xbf, 0x9f, 0x81, 0x43, 0xb3, 0x2e, 0x88, 0x31, 0x47, 0xba, 0x2c,
	0xa9, 0xe0, 0x42, 0x0e, 0x55, 0xc5, 0xeb, 0xc4, 0x20, 0xbd, 0xa6, 0x4b, 0x8c, 0xdf, 0x05, 0x8c,
	0x6e, 0x09, 0x15, 0xe3, 0x63, 0xfd, 0x6f, 0x41, 0xd9, 0x1c, 0x5f, 0x2a, 0x34, 0x2c, 0xc7, 0xd0,
	0xaf, 0x0c, 0x52, 0x92, 0xea, 0x48, 0x4c, 0xc4, 0x45, 0x38, 0x0f, 0xea, 0xe7, 0x4c, 0xcb, 0x13,
	0x18, 0x64, 0x45, 0xbe, 0x4a, 0x2a, 0xca, 0x22, 0xcf, 0x3a, 0xfd, 0xfa, 0xbd, 0xa0, 0x4c, 0x9e,
	0xc3, 0x3e, 0xbe, 0x95, 0x29, 0x61, 0xa2, 0x15, 0x63, 0xb4, 0x67, 0x5d, 0xd8, 0x48, 0x77, 0x8a,
	0x51, 0x1e, 0x80, 0x97, 0xea, 0xa8, 0x67, 0x75, 0x2f, 0xd5, 0xf2, 0x14, 0x42, 0x9b, 0xcf, 0x2e,
	0xf3, 0xad, 0x3c, 0x30, 0x4d, 0x90, 0xf8, 0x53, 0xc0, 0xf1, 0xef, 0x6c, 0xa6, 0x2c, 0x72, 0x83,
	0xee, 0x9c, 0x70, 0xe7, 0xba, 0xc9, 0x3d, 0x27, 0xf9, 0xbf, 0xf1, 0xba, 0x68, 0xbe, 0x8b, 0x76,
	0x06, 0xb0, 0x24, 0x85, 0x8c, 0x3a, 0x51, 0xdc, 0x10, 0x84, 0x8d, 0x32, 0xe5, 0xda, 0xae, 0xca,
	0x7a, 0xab, 0xb5, 0x83, 0x8d, 0xdd, 0x28, 0x53, 0x8e, 0x1f, 0x40, 0xde, 0x23, 0x6f, 0x5d, 0xf1,
	0x04, 0x86, 0xdf, 0x78, 0x3f, 0x18, 0xd0, 0x12, 0xce, 0x74, 0xfc, 0x21, 0xe0, 0xc8, 0xd9, 0xb8,
	0xbb, 0x62, 0x7a, 0x7f, 0x14, 0x83, 0x2d, 0xb9, 0xdf, 0x16, 0x83, 0x6a, 0x9b, 0x62, 0x6e, 0xc6,
	0x4f, 0xa3, 0x15, 0xe6, 0xf6, 0x32, 0xaf, 0xba, 0x87, 0xf9, 0x1c, 0x58, 0xed, 0xfa, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x3e, 0xc2, 0x9d, 0x1c, 0xc0, 0x02, 0x00, 0x00,
}
