// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpsertUserInfoRequest struct {
	UserId               string          `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data                 *_struct.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpsertUserInfoRequest) Reset()         { *m = UpsertUserInfoRequest{} }
func (m *UpsertUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertUserInfoRequest) ProtoMessage()    {}
func (*UpsertUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *UpsertUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertUserInfoRequest.Unmarshal(m, b)
}
func (m *UpsertUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpsertUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertUserInfoRequest.Merge(m, src)
}
func (m *UpsertUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertUserInfoRequest.Size(m)
}
func (m *UpsertUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertUserInfoRequest proto.InternalMessageInfo

func (m *UpsertUserInfoRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpsertUserInfoRequest) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateUserRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserPrimaryKey struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPrimaryKey) Reset()         { *m = UserPrimaryKey{} }
func (m *UserPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserPrimaryKey) ProtoMessage()    {}
func (*UserPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *UserPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPrimaryKey.Unmarshal(m, b)
}
func (m *UserPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPrimaryKey.Merge(m, src)
}
func (m *UserPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserPrimaryKey.Size(m)
}
func (m *UserPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserPrimaryKey proto.InternalMessageInfo

func (m *UserPrimaryKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserPrimaryKeyList struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPrimaryKeyList) Reset()         { *m = UserPrimaryKeyList{} }
func (m *UserPrimaryKeyList) String() string { return proto.CompactTextString(m) }
func (*UserPrimaryKeyList) ProtoMessage()    {}
func (*UserPrimaryKeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *UserPrimaryKeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPrimaryKeyList.Unmarshal(m, b)
}
func (m *UserPrimaryKeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPrimaryKeyList.Marshal(b, m, deterministic)
}
func (m *UserPrimaryKeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPrimaryKeyList.Merge(m, src)
}
func (m *UserPrimaryKeyList) XXX_Size() int {
	return xxx_messageInfo_UserPrimaryKeyList.Size(m)
}
func (m *UserPrimaryKeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPrimaryKeyList.DiscardUnknown(m)
}

var xxx_messageInfo_UserPrimaryKeyList proto.InternalMessageInfo

func (m *UserPrimaryKeyList) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetUserListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListRequest) Reset()         { *m = GetUserListRequest{} }
func (m *GetUserListRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserListRequest) ProtoMessage()    {}
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *GetUserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListRequest.Unmarshal(m, b)
}
func (m *GetUserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListRequest.Marshal(b, m, deterministic)
}
func (m *GetUserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListRequest.Merge(m, src)
}
func (m *GetUserListRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserListRequest.Size(m)
}
func (m *GetUserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListRequest proto.InternalMessageInfo

func (m *GetUserListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetUserListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetUserListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetUserListResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListResponse) Reset()         { *m = GetUserListResponse{} }
func (m *GetUserListResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserListResponse) ProtoMessage()    {}
func (*GetUserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *GetUserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListResponse.Unmarshal(m, b)
}
func (m *GetUserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListResponse.Marshal(b, m, deterministic)
}
func (m *GetUserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListResponse.Merge(m, src)
}
func (m *GetUserListResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserListResponse.Size(m)
}
func (m *GetUserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListResponse proto.InternalMessageInfo

func (m *GetUserListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetUserListResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AddUserRelationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelationId           string   `protobuf:"bytes,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRelationRequest) Reset()         { *m = AddUserRelationRequest{} }
func (m *AddUserRelationRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRelationRequest) ProtoMessage()    {}
func (*AddUserRelationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{7}
}

func (m *AddUserRelationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRelationRequest.Unmarshal(m, b)
}
func (m *AddUserRelationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRelationRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRelationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRelationRequest.Merge(m, src)
}
func (m *AddUserRelationRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRelationRequest.Size(m)
}
func (m *AddUserRelationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRelationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRelationRequest proto.InternalMessageInfo

func (m *AddUserRelationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddUserRelationRequest) GetRelationId() string {
	if m != nil {
		return m.RelationId
	}
	return ""
}

type UserRelationPrimaryKey struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RelationId           string   `protobuf:"bytes,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRelationPrimaryKey) Reset()         { *m = UserRelationPrimaryKey{} }
func (m *UserRelationPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserRelationPrimaryKey) ProtoMessage()    {}
func (*UserRelationPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{8}
}

func (m *UserRelationPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRelationPrimaryKey.Unmarshal(m, b)
}
func (m *UserRelationPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRelationPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserRelationPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRelationPrimaryKey.Merge(m, src)
}
func (m *UserRelationPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserRelationPrimaryKey.Size(m)
}
func (m *UserRelationPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRelationPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserRelationPrimaryKey proto.InternalMessageInfo

func (m *UserRelationPrimaryKey) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRelationPrimaryKey) GetRelationId() string {
	if m != nil {
		return m.RelationId
	}
	return ""
}

type UserInfoPrimaryKey struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoPrimaryKey) Reset()         { *m = UserInfoPrimaryKey{} }
func (m *UserInfoPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserInfoPrimaryKey) ProtoMessage()    {}
func (*UserInfoPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{9}
}

func (m *UserInfoPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoPrimaryKey.Unmarshal(m, b)
}
func (m *UserInfoPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserInfoPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoPrimaryKey.Merge(m, src)
}
func (m *UserInfoPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserInfoPrimaryKey.Size(m)
}
func (m *UserInfoPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoPrimaryKey proto.InternalMessageInfo

func (m *UserInfoPrimaryKey) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ResetPasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{10}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SendMessageToEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	BaseUrl              string   `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageToEmailRequest) Reset()         { *m = SendMessageToEmailRequest{} }
func (m *SendMessageToEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageToEmailRequest) ProtoMessage()    {}
func (*SendMessageToEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{11}
}

func (m *SendMessageToEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageToEmailRequest.Unmarshal(m, b)
}
func (m *SendMessageToEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageToEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageToEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageToEmailRequest.Merge(m, src)
}
func (m *SendMessageToEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageToEmailRequest.Size(m)
}
func (m *SendMessageToEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageToEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageToEmailRequest proto.InternalMessageInfo

func (m *SendMessageToEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendMessageToEmailRequest) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *SendMessageToEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserWithAuth struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RefreshToken         string   `protobuf:"bytes,9,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessToken          string   `protobuf:"bytes,10,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserWithAuth) Reset()         { *m = UserWithAuth{} }
func (m *UserWithAuth) String() string { return proto.CompactTextString(m) }
func (*UserWithAuth) ProtoMessage()    {}
func (*UserWithAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{12}
}

func (m *UserWithAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWithAuth.Unmarshal(m, b)
}
func (m *UserWithAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWithAuth.Marshal(b, m, deterministic)
}
func (m *UserWithAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWithAuth.Merge(m, src)
}
func (m *UserWithAuth) XXX_Size() int {
	return xxx_messageInfo_UserWithAuth.Size(m)
}
func (m *UserWithAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWithAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserWithAuth proto.InternalMessageInfo

func (m *UserWithAuth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserWithAuth) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserWithAuth) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserWithAuth) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserWithAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserWithAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserWithAuth) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UserWithAuth) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *UserWithAuth) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *UserWithAuth) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*UpsertUserInfoRequest)(nil), "auth_service.UpsertUserInfoRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "auth_service.CreateUserRequest")
	proto.RegisterType((*UserPrimaryKey)(nil), "auth_service.UserPrimaryKey")
	proto.RegisterType((*UserPrimaryKeyList)(nil), "auth_service.UserPrimaryKeyList")
	proto.RegisterType((*GetUserListRequest)(nil), "auth_service.GetUserListRequest")
	proto.RegisterType((*GetUserListResponse)(nil), "auth_service.GetUserListResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "auth_service.UpdateUserRequest")
	proto.RegisterType((*AddUserRelationRequest)(nil), "auth_service.AddUserRelationRequest")
	proto.RegisterType((*UserRelationPrimaryKey)(nil), "auth_service.UserRelationPrimaryKey")
	proto.RegisterType((*UserInfoPrimaryKey)(nil), "auth_service.UserInfoPrimaryKey")
	proto.RegisterType((*ResetPasswordRequest)(nil), "auth_service.ResetPasswordRequest")
	proto.RegisterType((*SendMessageToEmailRequest)(nil), "auth_service.SendMessageToEmailRequest")
	proto.RegisterType((*UserWithAuth)(nil), "auth_service.UserWithAuth")
}

func init() {
	proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90)
}

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 742 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xeb, 0x6e, 0xda, 0x4c,
	0x10, 0x0d, 0x36, 0x10, 0x18, 0xf2, 0x45, 0x5f, 0xb6, 0xb9, 0x10, 0x92, 0x2a, 0x74, 0x7f, 0x54,
	0x48, 0x55, 0x89, 0x94, 0x3e, 0x01, 0xb9, 0xa8, 0x42, 0xbd, 0x28, 0x72, 0x82, 0x2a, 0x45, 0xaa,
	0xd0, 0x82, 0x07, 0xb0, 0x6a, 0x6c, 0xba, 0xbb, 0x6e, 0xc5, 0xc3, 0xf4, 0x0d, 0xda, 0x87, 0xe8,
	0x9b, 0x55, 0xbb, 0x6b, 0x83, 0x6d, 0x02, 0xad, 0xf2, 0x8f, 0x33, 0x67, 0x38, 0x33, 0xb3, 0x73,
	0x31, 0x90, 0x48, 0x20, 0xef, 0x0b, 0xe4, 0xdf, 0xbc, 0x21, 0xb6, 0x67, 0x3c, 0x94, 0x21, 0xd9,
	0x61, 0x91, 0x9c, 0x24, 0xb6, 0x06, 0x28, 0x64, 0x98, 0xc6, 0xc9, 0x38, 0x0c, 0xc7, 0x3e, 0x9e,
	0x6b, 0x34, 0x88, 0x46, 0xe7, 0x38, 0x9d, 0xc9, 0x79, 0x4c, 0x9e, 0xe6, 0x49, 0x21, 0x79, 0x34,
	0x94, 0x86, 0xa5, 0x9f, 0xe1, 0xa0, 0x37, 0x13, 0xc8, 0x65, 0x4f, 0x20, 0xef, 0x06, 0xa3, 0xd0,
	0xc1, 0xaf, 0x11, 0x0a, 0x49, 0x8e, 0x60, 0x5b, 0xe7, 0xe0, 0xb9, 0xf5, 0x42, 0xb3, 0xd0, 0xaa,
	0x3a, 0x65, 0x05, 0xbb, 0x2e, 0x79, 0x05, 0x45, 0x97, 0x49, 0x56, 0xb7, 0x9a, 0x85, 0x56, 0xed,
	0xe2, 0xa8, 0x6d, 0xe4, 0xdb, 0x89, 0x7c, 0xfb, 0x4e, 0xcb, 0x3b, 0xda, 0x89, 0xfe, 0x28, 0xc0,
	0xde, 0x15, 0x47, 0x26, 0x51, 0xe9, 0x27, 0xda, 0xcf, 0x01, 0x46, 0x1e, 0x17, 0xb2, 0x1f, 0xb0,
	0x29, 0xc6, 0xf2, 0x55, 0x6d, 0xf9, 0xc8, 0xa6, 0x48, 0x4e, 0xa0, 0xea, 0xb3, 0x84, 0xb5, 0x34,
	0x5b, 0x51, 0x06, 0x4d, 0xee, 0x43, 0x69, 0x36, 0x09, 0x03, 0xac, 0xdb, 0x9a, 0x30, 0x80, 0x34,
	0xa0, 0xa2, 0xd2, 0xd3, 0xff, 0x28, 0x9a, 0x7f, 0x24, 0x58, 0x71, 0x33, 0x26, 0xc4, 0xf7, 0x90,
	0xbb, 0xf5, 0x92, 0xe1, 0x12, 0x4c, 0x9b, 0xb0, 0xab, 0x12, 0xbb, 0xe5, 0xde, 0x94, 0xf1, 0xf9,
	0x3b, 0x9c, 0x93, 0x5d, 0xb0, 0x16, 0x25, 0x5b, 0x9e, 0x4b, 0x5f, 0x02, 0xc9, 0x7a, 0xbc, 0xf7,
	0x84, 0x24, 0xff, 0x83, 0xed, 0xb9, 0xa2, 0x5e, 0x68, 0xda, 0xad, 0xaa, 0xa3, 0x7e, 0xd2, 0x07,
	0x20, 0x6f, 0x51, 0xbf, 0xa2, 0x72, 0x48, 0x2a, 0xdd, 0x87, 0x92, 0xef, 0x4d, 0x3d, 0xa9, 0x05,
	0x4b, 0x8e, 0x01, 0xe4, 0x10, 0xca, 0xe1, 0x68, 0x24, 0x50, 0xea, 0xea, 0x4a, 0x4e, 0x8c, 0x94,
	0x5d, 0x20, 0xe3, 0xc3, 0x49, 0x5c, 0x5c, 0x8c, 0x68, 0x0f, 0x9e, 0x65, 0xb4, 0xc5, 0x2c, 0x0c,
	0x84, 0x7e, 0x8a, 0x61, 0x18, 0x05, 0x0b, 0x71, 0x0d, 0x48, 0x0b, 0x4a, 0xaa, 0x74, 0x51, 0xb7,
	0x9a, 0x76, 0xab, 0x76, 0x41, 0xda, 0xe9, 0xb1, 0x69, 0xeb, 0x36, 0x18, 0x07, 0xfa, 0xab, 0x00,
	0x7b, 0xbd, 0x99, 0x9b, 0x6b, 0x4e, 0xee, 0x01, 0x72, 0xcd, 0xb2, 0x36, 0x36, 0xcb, 0x5e, 0xd7,
	0xac, 0xe2, 0xba, 0x66, 0x95, 0x36, 0x34, 0xab, 0x9c, 0x6b, 0x96, 0x03, 0x87, 0x1d, 0xd7, 0x35,
	0xb9, 0xfa, 0x4c, 0x7a, 0x61, 0xf0, 0xd7, 0x61, 0x3d, 0x83, 0x1a, 0x8f, 0x7d, 0x15, 0x69, 0xb2,
	0x87, 0xc4, 0xd4, 0xd5, 0x9a, 0x69, 0xc1, 0xd4, 0x20, 0x3c, 0x5d, 0xf3, 0xb5, 0x19, 0x19, 0xb5,
	0x4d, 0xff, 0xa0, 0x47, 0x19, 0xec, 0x3b, 0x28, 0x50, 0xde, 0xc6, 0x75, 0xa6, 0x66, 0x47, 0x86,
	0x5f, 0x30, 0x88, 0xdd, 0x0d, 0xc8, 0x3c, 0x90, 0x95, 0x7d, 0xa0, 0x74, 0x08, 0x3b, 0x13, 0x62,
	0x00, 0xc7, 0x77, 0x18, 0xb8, 0x1f, 0x50, 0x08, 0x36, 0xc6, 0xfb, 0xf0, 0x66, 0xca, 0x3c, 0x3f,
	0x15, 0x07, 0x15, 0x4e, 0xe2, 0x68, 0x40, 0x8e, 0xa1, 0x32, 0x60, 0x02, 0xfb, 0x11, 0xf7, 0xe3,
	0x38, 0xdb, 0x0a, 0xf7, 0xb8, 0xbf, 0x4c, 0xcc, 0x4e, 0x25, 0x46, 0x7f, 0x5a, 0xb0, 0xa3, 0xca,
	0xfe, 0xe4, 0xc9, 0x49, 0x27, 0x92, 0x93, 0x95, 0x41, 0x5a, 0x0c, 0x83, 0x95, 0x1e, 0x86, 0xec,
	0x78, 0xd9, 0x1b, 0xc7, 0xab, 0x98, 0x1b, 0xaf, 0x27, 0x0e, 0x92, 0x8a, 0x39, 0xd4, 0x47, 0xc9,
	0xed, 0x33, 0x59, 0xdf, 0x36, 0x31, 0x63, 0x4b, 0x47, 0x9f, 0xa7, 0x48, 0xaf, 0x85, 0xa6, 0x2b,
	0x86, 0x8e, 0x2d, 0x1d, 0x49, 0x28, 0xec, 0x70, 0x1c, 0x71, 0x14, 0x93, 0x7b, 0xfd, 0x0a, 0x55,
	0xed, 0x90, 0xb1, 0x91, 0x26, 0xd4, 0xd8, 0x70, 0x88, 0x42, 0x18, 0x17, 0xd0, 0x2e, 0x69, 0xd3,
	0xc5, 0x6f, 0x1b, 0x6a, 0xea, 0xb9, 0xee, 0xcc, 0x62, 0x92, 0x2b, 0x80, 0xe5, 0xa1, 0x24, 0x67,
	0xd9, 0xad, 0x5d, 0x39, 0xa1, 0x8d, 0x47, 0xd6, 0x9a, 0x6e, 0x91, 0x0e, 0xd4, 0xe2, 0x43, 0x71,
	0x39, 0xef, 0x5e, 0x93, 0xd3, 0x55, 0xa7, 0xe5, 0x40, 0xae, 0x91, 0xb8, 0x5f, 0x48, 0xe8, 0x43,
	0xd7, 0xcc, 0x3a, 0xad, 0x9e, 0xb8, 0xc6, 0x8b, 0x0d, 0x1e, 0xe6, 0x50, 0xd1, 0x2d, 0x55, 0xdd,
	0xf2, 0xd2, 0xe4, 0xab, 0x5b, 0xb9, 0x41, 0x6b, 0x52, 0xbb, 0x06, 0xb8, 0x46, 0x1f, 0x63, 0x91,
	0xcd, 0xc5, 0x1d, 0xae, 0x7c, 0x97, 0x6e, 0xd4, 0x37, 0x91, 0x6e, 0x91, 0x2e, 0xfc, 0x97, 0x59,
	0x37, 0x42, 0xb3, 0x42, 0x8f, 0xed, 0xe2, 0xe3, 0x09, 0x5d, 0x1e, 0x3d, 0x1c, 0x8c, 0x31, 0xd0,
	0x11, 0xce, 0xd3, 0xfc, 0xa0, 0xac, 0x6d, 0x6f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x21,
	0xf7, 0x16, 0xc7, 0x07, 0x00, 0x00,
}
